server:
  port: 2002

spring:
  application:
    name: seata-account-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    #driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    #url: jdbc:mysql://192.168.211.168:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      test-while-idle: false

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 50000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 50000

mybatis:
  mapper-locations: classpath:mapper/*.xml
